# Generated by Django 3.1 on 2020-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default='108DF7', help_text='User Id - Primary Key', primary_key=True, serialize=False),
        ),
    ]
