# Generated by Django 3.1 on 2020-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200812_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeZone',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='C4DB5A900', help_text='User Id - Primary Key', max_length=9, primary_key=True, serialize=False),
        ),
    ]
